# Generated by Django 4.2.17 on 2024-12-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cagegory',
            new_name='Category',
        ),
    ]
